apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apigo
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: apigo
    spec:
      containers:
      - name: apigo
        image: ndcontainerregistry.azurecr.io/apigo:redis-v1
        ports:
        - containerPort: 8084
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: apigo
spec:
  type: LoadBalancer
  ports:
  - port: 8084
  selector:
    app: apigo