apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apinetcore-back
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: apinetcore-back
    spec:
      containers:
      - name: apinetcore-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: apinetcore-back
spec:
  ports:
  - port: 6379
  selector:
    app: apinetcore-back
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apinetcore
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: apinetcore
    spec:
      containers:
      - name: apinetcore
        image: ndcontainerregistry.azurecr.io/apinetcore:redis-v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "apinetcore-back"
---
apiVersion: v1
kind: Service
metadata:
  name: apinetcore
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: apinetcore